window.QUESTIONS = [
  { t: "Analisis documental", d: "Base", q: "Segun el material, el analisis documental busca representar un documento bajo una forma diferente para facilitar...", a: 1, o: ["La decoracion visual del documento", "La consulta o recuperacion por especialistas interesados", "La compra de nuevos materiales", "La eliminacion de documentos duplicados"], e: "El analisis documental traduce, resume o indiza para facilitar la consulta y recuperacion." },
  { t: "Analisis documental", d: "Base", q: "Una definicion breve de analisis documental es...", a: 2, o: ["Copiar literalmente todo el documento", "Ordenar libros por tamano fisico", "Extraer elementos caracteristicos del documento", "Disenar portadas de documentos"], e: "El PDF lo define como la operacion de extraer elementos caracteristicos y derivar palabras de representacion condensada." },
  { t: "Analisis documental", d: "Media", q: "Cual NO aparece como objetivo del analisis documental?", a: 3, o: ["Identificar y localizar documentos", "Contribuir al conocimiento del contenido", "Objetividad y normalizacion", "Aumentar la extension del documento original"], e: "Los objetivos apuntan a identificar, recuperar, representar contenido y normalizar, no a extender el texto." },
  { t: "Analisis documental", d: "Base", q: "La tipologia del documento se puede observar por soporte fisico, difusion y...", a: 0, o: ["Contenido informativo", "Precio comercial", "Color de la cubierta", "Numero de autores"], e: "El material enumera soporte fisico, difusion y contenido informativo." },
  { t: "Analisis documental", d: "Media", q: "Cuales son categorias de difusion mencionadas?", a: 1, o: ["Textuales, graficos, sonoros", "Publicados, reservados e ineditos", "Primarios, secundarios y terciarios", "Resumen, indice y tesauro"], e: "La difusion se clasifica en publicados, reservados e ineditos." },
  { t: "Analisis documental", d: "Alta", q: "Las problematicas del analisis documental incluyen naturaleza linguistica, extralinguistica y...", a: 2, o: ["Naturaleza monetaria", "Indole juridica", "Indole documental", "Naturaleza editorial"], e: "La indole documental se relaciona con la tematica tratada." },
  { t: "Analisis documental", d: "Media", q: "En la cadena del procesamiento tecnico, el orden presentado es seleccion, adquisicion, catalogacion, clasificacion e...", a: 3, o: ["Inventario", "Circulacion", "Encuadernacion", "Indizacion"], e: "La cadena termina con indizacion dentro de la secuencia mostrada." },
  { t: "Indizacion", d: "Base", q: "La indizacion consiste en representar el contenido del documento mediante...", a: 0, o: ["Terminos de indizacion extraidos de lenguajes documentales", "Firmas de usuarios frecuentes", "Imagenes decorativas", "Codigos de barras exclusivamente"], e: "La indizacion usa terminos de indizacion procedentes de lenguajes documentales." },
  { t: "Indizacion", d: "Media", q: "Las dos operaciones principales del analisis de contenido son...", a: 2, o: ["Compra y descarte", "Catalogacion y circulacion", "Resumen e indizacion", "Encuadernacion y restauracion"], e: "El analisis de contenido establece puntos de acceso por materias mediante resumen e indizacion." },
  { t: "Indizacion", d: "Base", q: "Un descriptor es una palabra o grupo de palabras escogidas para representar...", a: 1, o: ["La editorial del libro", "Sin ambiguedad un concepto de un documento", "El precio de adquisicion", "La fecha de devolucion"], e: "El descriptor se elige entre terminos equivalentes para representar un concepto sin ambiguedad." },
  { t: "Indizacion", d: "Media", q: "Un no descriptor es...", a: 3, o: ["Un termino obligatorio para indizar", "Un campo MARC de autores", "Una palabra vacia sin significado", "Un termino con prohibicion de uso y reenvio a descriptores"], e: "El no descriptor remite desde un termino no preferente hacia un descriptor utilizable." },
  { t: "Indizacion", d: "Alta", q: "Diferencia correcta entre descriptores libres y palabras clave:", a: 0, o: ["Los descriptores libres indizan conceptos; las palabras clave suelen indizar uniterminos", "Los descriptores libres son siempre automaticos", "Las palabras clave siempre salen de un tesauro controlado", "No existe diferencia en el material"], e: "El PDF contrapone indizacion humana de conceptos frente a extraccion automatica de uniterminos." },

  { t: "Resumenes documentales", d: "Base", q: "La norma citada define resumen como una representacion abreviada y precisa del contenido, sin...", a: 2, o: ["Titulo ni autor", "Paginas ni capitulos", "Interpretacion ni critica", "Palabras significativas"], e: "El resumen documental no debe incluir interpretacion ni critica del autor del resumen." },
  { t: "Resumenes documentales", d: "Base", q: "Una pregunta que Lancaster recomienda al indizador es:", a: 1, o: ["Cuanto cuesta imprimir el documento?", "De que trata el documento?", "Quien diseno la portada?", "Cual es el color institucional?"], e: "Lancaster propone preguntar de que trata, por que esta en la coleccion y que interesa al usuario." },
  { t: "Resumenes documentales", d: "Media", q: "Cual criterio general significa emplear el menor numero de terminos?", a: 0, o: ["Brevedad", "Textualidad", "Exhaustividad", "Objetividad"], e: "Brevedad se asocia con usar el menor numero de terminos." },
  { t: "Resumenes documentales", d: "Media", q: "El criterio de exhaustividad pide...", a: 3, o: ["Usar muchas citas", "Cambiar el sentido del texto", "Evitar todo resultado", "No omitir partes sustanciales"], e: "Exhaustividad significa cubrir las partes sustanciales sin dejarlas fuera." },
  { t: "Resumenes documentales", d: "Media", q: "Un resumen independiente debe...", a: 2, o: ["Depender de graficos del documento", "Citar todas las referencias", "Entenderse por si mismo", "Incluir opiniones del resumidor"], e: "Independiente significa que se entiende sin acudir al documento original." },
  { t: "Resumenes documentales", d: "Base", q: "Cual de estos aparece como elemento posible de un resumen?", a: 1, o: ["Color de portada", "Metodologia", "Numero de inventario", "Tipo de papel"], e: "El material lista introduccion, objetivo, aspectos teoricos, metodologia, resultados y conclusiones." },
  { t: "Resumenes documentales", d: "Media", q: "Segun los lineamientos comunes, se debe dejar por fuera...", a: 0, o: ["Ejemplos, definiciones y explicaciones", "El objetivo del documento siempre", "Todos los resultados", "Todas las palabras significativas"], e: "Los lineamientos recomiendan excluir ejemplos, definiciones, graficos, tablas, referencias y lo marginal." },
  { t: "Resumenes documentales", d: "Alta", q: "Una recomendacion de redaccion es iniciar con...", a: 3, o: ["Una critica personal", "Una referencia bibliografica completa", "Un listado de siglas poco frecuentes", "Una frase que represente la idea basica del tema principal"], e: "El resumen debe arrancar con la idea basica del tema principal e indicar el tipo de documento." },

  { t: "Tipos de resumen", d: "Base", q: "El resumen indicativo o descriptivo se caracteriza por ser...", a: 0, o: ["Corto y general", "Siempre mayor a 500 palabras", "Una reseña con juicio critico", "Un registro MARC completo"], e: "El indicativo es corto, general y suele ir de 25 a 50 palabras." },
  { t: "Tipos de resumen", d: "Media", q: "El resumen indicativo normalmente NO incluye...", a: 2, o: ["Objetivo", "Resultados", "Metodologia ni conclusiones", "Tema general"], e: "El PDF indica que contiene objetivo y resultados, pero no metodologia ni conclusiones." },
  { t: "Tipos de resumen", d: "Base", q: "El resumen informativo contiene objetivos, metodos, resultados y conclusiones, y suele tener...", a: 1, o: ["25 a 50 palabras", "100 a 300 palabras", "Una sola frase", "Mas de 1000 palabras siempre"], e: "El informativo es el resumen documental por excelencia y se ubica entre 100 y 300 palabras." },
  { t: "Tipos de resumen", d: "Alta", q: "El resumen analitico se distingue porque...", a: 3, o: ["Solo enumera palabras clave", "Elimina resultados y conclusiones", "Se usa solo en cuentos infantiles", "Puede sobrepasar 500 palabras y exige alto detalle"], e: "Es el nivel mas detallado, poco habitual por el tiempo que consume." },
  { t: "Tipos de resumen", d: "Media", q: "El resumen literario debe contener trama, personajes principales, donde y cuando sucede la obra y...", a: 0, o: ["Desenlace final", "Indicadores MARC", "Terminos especificos", "Codigo de barras"], e: "El PDF incluye desenlace final, aunque advierte no hacer spoiler de la trama." },
  { t: "Tipos de resumen", d: "Media", q: "En MARC Bibliografico, la nota de sumario o resumen se registra en el campo...", a: 2, o: ["245", "650", "520", "856"], e: "El campo 520 se usa para sumario, reseña, alcance y contenido, resumen o aviso de contenido." },
  { t: "Tipos de resumen", d: "Alta", q: "En el campo 520, el primer indicador 3 corresponde a...", a: 1, o: ["Reseña", "Resumen", "Alcance y contenido", "Aviso sobre contenido"], e: "Los indicadores presentados son #: sumario, 1: reseña, 2: alcance y contenido, 3: resumen, 4: aviso." },

  { t: "Lenguajes documentales", d: "Base", q: "Un lenguaje documental es un vocabulario o sistema artificial de signos normalizados que facilita...", a: 0, o: ["La representacion del contenido de los documentos", "La impresion a color", "La compra de libros", "El calculo de multas"], e: "Su funcion central es representar contenido y facilitar recuperacion." },
  { t: "Lenguajes documentales", d: "Media", q: "Cual es un objetivo de los lenguajes documentales?", a: 3, o: ["Ocultar alternativas de busqueda", "Aumentar ruido documental", "Eliminar la normalizacion", "Reducir esfuerzo y tiempo del usuario"], e: "El material menciona reducir esfuerzo y tiempo, normalizar terminologias y mostrar alternativas." },
  { t: "Lenguajes documentales", d: "Base", q: "Los lenguajes libres tienen como ventaja ser baratos, rapidos y terminologicamente ricos, pero presentan...", a: 2, o: ["Demasiada normalizacion", "Ausencia total de terminos", "Ambiguedad, silencio y ruido documental", "Solo documentos impresos"], e: "La ambiguedad puede generar silencio y ruido documental y demasiados resultados." },
  { t: "Lenguajes documentales", d: "Media", q: "Un listado de descriptores libres es...", a: 1, o: ["Un tesauro con relaciones jerarquicas obligatorias", "Un vocabulario monolingue alfabético elegido por el analista sin lista previa", "Una lista exclusiva de autores", "Un campo Dublin Core"], e: "No es lenguaje controlado; el analista selecciona los terminos sin verificar en lista establecida." },
  { t: "Lenguajes documentales", d: "Alta", q: "El lenguaje documental traslada dificultad al proceso de indizacion para producir facilidad en...", a: 0, o: ["La recuperacion", "La impresion", "La encuadernacion", "La portada"], e: "La dificultad se asume al indizar para facilitar luego la recuperacion." },

  { t: "Tesauros", d: "Base", q: "Los lenguajes postcoordinados combinan los terminos en el momento de...", a: 1, o: ["La adquisicion", "La recuperacion", "La impresion", "La restauracion"], e: "El material define los postcoordinados como lenguajes que combinan terminos al recuperar." },
  { t: "Tesauros", d: "Media", q: "En un tesauro, las relaciones de equivalencia aplican entre...", a: 2, o: ["Autores y editoriales", "Campos y subcampos MARC", "Terminos preferentes y no preferentes", "Fechas y lugares solamente"], e: "USE y UP conectan formas preferentes y no preferentes." },
  { t: "Tesauros", d: "Media", q: "Si 'bibliobus USE biblioteca movil', entonces 'bibliobus' funciona como...", a: 3, o: ["Termino generico", "Termino especifico", "Nota de historia", "No preferente que remite al preferente"], e: "USE indica que debe usarse el descriptor preferente indicado." },
  { t: "Tesauros", d: "Media", q: "Las relaciones jerarquicas se establecen cuando el alcance de un concepto queda dentro del alcance de otro. Sus etiquetas generales son...", a: 0, o: ["TG y TE", "TR y NH", "DEF y USE", "MARC y DC"], e: "TG es termino generico y TE es termino especifico." },
  { t: "Tesauros", d: "Alta", q: "La relacion generica conecta una clase o categoria con...", a: 1, o: ["Una nota de historia", "Sus miembros o especies", "Una fuente bibliografica", "Un acronimo ambiguo"], e: "Ejemplo del material: todos los loros son pajaros, algunos pajaros son loros." },
  { t: "Tesauros", d: "Alta", q: "La relacion jerarquica todo-parte aplica a casos donde una parte pertenece a un todo, como...", a: 2, o: ["UNICEF y su forma desarrollada", "Bibliobus y biblioteca movil", "Puntarenas y Costa Rica", "520 y resumen"], e: "El PDF usa Costa Rica TEP Puntarenas y Puntarenas TGP Costa Rica." },
  { t: "Tesauros", d: "Alta", q: "La relacion enumerativa conecta un concepto general con una instancia individual, por ejemplo...", a: 3, o: ["Casa y vivienda", "Ropa y confeccion", "Bibliobus y biblioteca movil", "Himalaya y regiones de montana"], e: "Himalaya es una instancia nombrada dentro de regiones de montana." },
  { t: "Tesauros", d: "Media", q: "Las relaciones asociativas se representan con...", a: 0, o: ["TR", "TG", "TE", "NH"], e: "TR significa termino relacionado y se aplica reciprocamente." },
  { t: "Tesauros", d: "Alta", q: "Cual par ejemplifica relacion asociativa segun el material?", a: 1, o: ["Animales y mamiferos", "Pajaros y ornitologia", "Casa y vivienda", "520 y sumario"], e: "Pajaros TR ornitologia muestra asociacion semantica sin jerarquia." },
  { t: "Tesauros", d: "Media", q: "Para homografos u homonimos en un tesauro se debe...", a: 2, o: ["Eliminarlos siempre", "Usar solo mayusculas", "Clarificar el significado de cada termino", "Convertirlos en campos MARC"], e: "Ejemplo: gatos (animales domesticos) y gatos (equipos de levantamiento de pesos)." },
  { t: "Tesauros", d: "Media", q: "Segun la gramatica de terminos, los adverbios en tesauros...", a: 3, o: ["Son obligatorios", "Son mejores que sustantivos", "Deben iniciar todas las frases", "No deberian usarse"], e: "El material indica que los adverbios no deberian usarse, menos frases que comiencen con ellos." },
  { t: "Tesauros", d: "Alta", q: "Sobre acronimos en tesauros, la recomendacion correcta es...", a: 0, o: ["No usarlos si generan ambiguedad; usarlos si son reconocidos sin ambiguedad", "Usarlos siempre aunque sean desconocidos", "Prohibir UNICEF aunque sea claro", "Preferir siempre simbolos especiales"], e: "MICITT se remite a su forma completa si puede ser ambiguo; UNICEF puede usarse si es ampliamente reconocido." },

  { t: "Registros bibliograficos", d: "Base", q: "En el ejemplo de El Principito, el campo 001 corresponde a...", a: 1, o: ["ISBN", "Numero de control", "Titulo", "Nota de sumario"], e: "El registro muestra 001 como numero de control." },
  { t: "Registros bibliograficos", d: "Media", q: "El campo 020 registra...", a: 0, o: ["ISBN", "Idioma", "Nota de lengua", "Localizacion electronica"], e: "020 se usa para el Numero Internacional Normalizado para Libros." },
  { t: "Registros bibliograficos", d: "Media", q: "El campo 245 se usa para...", a: 2, o: ["Tipo de soporte", "Punto cronologico", "Mencion de titulo", "Termino no controlado"], e: "245 contiene la mencion de titulo y responsabilidad." },
  { t: "Registros bibliograficos", d: "Media", q: "El campo 600 se utiliza cuando el punto de acceso tematico es...", a: 3, o: ["Un lugar geografico", "Un termino cronologico", "Una forma o genero", "El nombre de una persona"], e: "600 es punto de acceso adicional de materia - nombre de persona." },
  { t: "Registros bibliograficos", d: "Media", q: "El campo 648 corresponde a puntos de acceso de tipo...", a: 1, o: ["Geografico", "Cronologico", "Genero o forma", "Localizacion web"], e: "648 registra terminos cronologicos, como 1943." },
  { t: "Registros bibliograficos", d: "Alta", q: "El campo 650 se usa para puntos de acceso tematicos que provienen de una fuente controlada como...", a: 0, o: ["LEMB, tesauros o catalogos de autoridad de materia", "Solo redes sociales", "Unicamente inventarios locales", "Notas personales del lector"], e: "El PDF dice que 650 registra terminos de materia procedentes de fuentes controladas." },
  { t: "Registros bibliograficos", d: "Media", q: "El campo 651 registra...", a: 2, o: ["Nombres personales", "Terminos no controlados", "Nombre geografico", "Tipo de contenido"], e: "651 es punto de acceso adicional de materia - nombre geografico." },
  { t: "Registros bibliograficos", d: "Alta", q: "Cuando un termino es novedoso, no esta en ningun tesauro y es necesario para describir contenido, se puede usar...", a: 3, o: ["600", "650", "655", "653"], e: "653 es termino de indizacion no controlado." },
  { t: "Registros bibliograficos", d: "Media", q: "El campo 655 se usa para...", a: 1, o: ["ISBN", "Genero o forma", "Nombre de persona", "Origen de catalogacion"], e: "655 corresponde a termino de indizacion - genero o forma." },
  { t: "Registros bibliograficos", d: "Alta", q: "En el registro Dublin Core del ejemplo, dc.abstract corresponde a...", a: 0, o: ["La narracion/resumen de la obra", "El ISBN solamente", "La lengua original", "La editorial"], e: "dc.abstract contiene el resumen sobre el pequeno principe y su travesia." }
];

window.EXTRA_QUESTIONS = [
  { t: "Analisis documental", d: "Media", q: "Cuando el analisis documental traduce, resume o indiza, lo hace para cambiar el documento a una forma...", a: 2, o: ["Mas extensa que la original", "Decorativa y comercial", "Diferente de la original pero util para recuperar", "Reservada solo para archivo historico"], e: "La idea central es representar el documento de otra manera para facilitar consulta y recuperacion.", h: "Fijate en el verbo representar: no se trata de copiar ni adornar, sino de crear una version funcional para encontrar el contenido." },
  { t: "Analisis documental", d: "Alta", q: "Si una persona resume el contenido con sus creencias personales, aparece sobre todo una problematica de naturaleza...", a: 1, o: ["Linguistica", "Extralinguistica", "Tipografica", "Cronologica"], e: "La naturaleza extralinguistica incluye esquemas del autor y creencias del analista.", h: "La pista esta en lo que viene de fuera del texto: creencias, esquemas mentales y contexto del analista." },
  { t: "Analisis documental", d: "Base", q: "Un documento sonoro pertenece a la tipologia por...", a: 0, o: ["Soporte fisico", "Difusion", "Contenido informativo", "Campo MARC"], e: "Los documentos sonoros aparecen en la lista de soportes fisicos junto con graficos, iconograficos y audiovisuales.", h: "Preguntate si 'sonoro' describe el modo material/formato del documento, su publicacion o su nivel de informacion." },
  { t: "Analisis documental", d: "Media", q: "Un documento inedito se clasifica, segun la presentacion, por su...", a: 3, o: ["Soporte fisico", "Idioma", "Extension", "Difusion"], e: "En difusion aparecen publicados, reservados e ineditos.", h: "La palabra 'inedito' habla de si se publico o no, no del tema ni del soporte." },
  { t: "Indizacion", d: "Media", q: "El punto de acceso por materias se establece en la parte del analisis documental llamada...", a: 2, o: ["Descripcion fisica", "Adquisicion", "Analisis del contenido", "Mencion de edicion"], e: "El analisis de contenido identifica y representa la materia de los documentos para permitir recuperacion.", h: "Busca la parte que trabaja con la materia o tema del documento, no con datos editoriales." },
  { t: "Indizacion", d: "Alta", q: "Si un sistema devuelve demasiados resultados irrelevantes por ambiguedad terminologica, el problema se acerca a...", a: 1, o: ["Exhaustividad perfecta", "Ruido documental", "Catalogacion descriptiva", "Nota de sumario"], e: "Los lenguajes libres pueden producir ambiguedad, silencio y ruido documental.", h: "Ruido es cuando aparece demasiado que no sirve; silencio es cuando no aparece lo que si deberia aparecer." },
  { t: "Indizacion", d: "Alta", q: "Si un usuario no recupera documentos pertinentes porque el termino usado no coincide con el sistema, hablamos de...", a: 0, o: ["Silencio documental", "Resumen analitico", "Mencion de titulo", "Relacion partitiva"], e: "La ambiguedad y falta de control pueden producir silencio documental: documentos pertinentes no recuperados.", h: "Contrasta silencio con ruido: silencio es ausencia de resultados pertinentes; ruido es exceso de resultados no pertinentes." },
  { t: "Indizacion", d: "Media", q: "Las palabras clave se extraen de forma automatica principalmente a partir de titulo, resumen y a veces...", a: 3, o: ["Numero de control", "Codigo de barras", "Nombre del catalogador", "Texto completo"], e: "El material indica que cada vez mas se extraen del texto completo de documentos registrados.", h: "La pregunta apunta a la fuente textual de donde una computadora puede sacar terminos significativos." },

  { t: "Resumenes documentales", d: "Media", q: "Si un resumen agrega una opinion que el documento original no contiene, falla principalmente en el criterio de...", a: 1, o: ["Brevedad", "Objetividad", "Textualidad", "Soporte"], e: "El criterio objetivo indica no incluir afirmaciones ni aseveraciones no contenidas en el documento original.", h: "Busca el criterio que protege contra meter juicios, interpretaciones o afirmaciones externas." },
  { t: "Resumenes documentales", d: "Alta", q: "Un resumen que solo se entiende si el lector consulta el documento original incumple el criterio de ser...", a: 2, o: ["Exhaustivo", "Breve", "Independiente", "Automatizado"], e: "Independiente significa que debe entenderse por si mismo.", h: "La clave esta en la autonomia del texto: el resumen debe funcionar sin tener el original al lado." },
  { t: "Resumenes documentales", d: "Base", q: "Cual recomendacion ayuda a la recuperacion automatizada?", a: 0, o: ["Usar palabras significativas tomadas del texto", "Eliminar todos los terminos tecnicos", "Usar solo pronombres", "Evitar mencionar el tema principal"], e: "El material recomienda usar palabras significativas del texto para apoyar la recuperacion automatizada.", h: "Piensa como buscaria una computadora: necesita terminos con carga semantica, no palabras vacias." },
  { t: "Resumenes documentales", d: "Media", q: "Cual elemento del resumen responde al 'para que' del documento?", a: 3, o: ["Resultados", "Aspectos teoricos", "Introduccion", "Objetivo o proposito"], e: "El objetivo o proposito expresa la finalidad del documento.", h: "El 'para que' o intencion se relaciona con proposito, no con hallazgos finales." },
  { t: "Resumenes documentales", d: "Alta", q: "Segun los lineamientos, por que se omiten graficos, tablas y referencias en un resumen documental?", a: 2, o: ["Porque son ilegales", "Porque siempre son falsos", "Porque el resumen debe concentrarse en contenido esencial textual", "Porque solo importan los autores"], e: "Los lineamientos orientan a dejar fuera elementos accesorios para mantener brevedad y esencialidad.", h: "Relaciona esta respuesta con brevedad y esencialidad: el resumen no reproduce todos los apoyos del documento." },

  { t: "Tipos de resumen", d: "Base", q: "Cual tipo de resumen se considera el mas elemental por su cercania al indice?", a: 1, o: ["Analitico", "Indicativo", "Informativo", "Literario"], e: "El indicativo es el mas elemental y cercano al indice.", h: "El mas breve y general suele acercarse mas a un indice que a una explicacion completa." },
  { t: "Tipos de resumen", d: "Media", q: "Si un resumen incluye objetivos, metodos, resultados y conclusiones en 150 palabras, probablemente es...", a: 0, o: ["Informativo", "Indicativo", "Literario", "No descriptor"], e: "El informativo suele tener 100 a 300 palabras e incluye esos componentes.", h: "Mira dos pistas juntas: componentes completos y extension media." },
  { t: "Tipos de resumen", d: "Alta", q: "Un trabajo final de graduacion podria justificar un resumen...", a: 3, o: ["Indicativo de 25 palabras", "De palabras clave automaticas", "De campo 653", "Analitico y muy detallado"], e: "El resumen analitico se utiliza en informes y trabajos finales de graduacion por su mayor detalle.", h: "Cuando el documento es complejo y largo, el resumen que consume mas tiempo puede tener sentido." },
  { t: "Tipos de resumen", d: "Media", q: "En el campo 520, el primer indicador 1 significa...", a: 2, o: ["Sumario", "Resumen", "Reseña", "Aviso sobre contenido"], e: "En 520, el indicador 1 corresponde a reseña.", h: "Recuerda la secuencia del PDF: # sumario, 1 reseña, 2 alcance y contenido, 3 resumen, 4 aviso." },
  { t: "Tipos de resumen", d: "Alta", q: "El subcampo usado en 520 para colocar el sumario o resumen es...", a: 0, o: ["$a", "$2", "$x", "$z"], e: "El campo 520 usa el subcampo $a para sumario, etc.", h: "En varios campos MARC, $a suele contener el dato principal del campo." },

  { t: "Lenguajes documentales", d: "Media", q: "Normalizar o unificar terminologias sirve para...", a: 1, o: ["Hacer mas ambiguas las busquedas", "Mejorar consistencia entre indizacion y recuperacion", "Eliminar todos los sinonimos del idioma", "Evitar que existan materias"], e: "La normalizacion ayuda a que el sistema use terminos consistentes para representar y recuperar.", h: "Piensa en el problema de sinonimos: si cada analista usa una palabra distinta, recuperar se vuelve dificil." },
  { t: "Lenguajes documentales", d: "Alta", q: "Que afirmacion describe mejor la tension de un lenguaje documental?", a: 2, o: ["Es facil al indizar y dificil al recuperar", "No necesita reglas", "Exige mas cuidado al indizar para facilitar la recuperacion", "Solo sirve para portadas"], e: "El material dice que su dificultad esta en el proceso de indizacion, lo que se traduce en facilidad en la recuperacion.", h: "La carga de trabajo se mueve hacia quien organiza, para que quien busca encuentre mas facil." },
  { t: "Lenguajes documentales", d: "Media", q: "La indizacion social y la informacion temporal se asocian en el material con...", a: 0, o: ["Listados de descriptores libres", "Campo 655", "Resumen analitico", "Dublin Core"], e: "Los descriptores libres se usan en informacion temporal, audiovisual web e indizacion social.", h: "Busca una herramienta flexible y rapida, no una fuente controlada rigida." },
  { t: "Lenguajes documentales", d: "Alta", q: "Si un vocabulario no verifica previamente si los terminos existen en una lista establecida, entonces no es...", a: 3, o: ["Monolingue", "Alfabetico", "Humano", "Controlado"], e: "Los listados de descriptores libres no son lenguajes controlados.", h: "La palabra clave es verificar contra una lista autorizada: eso es justamente control terminologico." },

  { t: "Tesauros", d: "Base", q: "En un tesauro, USE indica que...", a: 1, o: ["El termino esta prohibido sin alternativa", "Debe usarse otro termino preferente", "Hay una relacion geografica", "El termino es un campo MARC"], e: "USE remite desde un termino no preferente hacia el descriptor preferente.", h: "USE funciona como una flecha: desde la forma no preferida hacia la forma que si debes usar." },
  { t: "Tesauros", d: "Media", q: "UP en un tesauro se usa para indicar...", a: 2, o: ["Un campo cronologico", "Una nota de contenido", "Usado por / termino no preferente asociado al preferente", "Una subdivision geografica"], e: "UP muestra los terminos no preferentes relacionados con el descriptor preferente.", h: "Si estas parado en el termino correcto, UP te muestra las variantes que remiten hacia el." },
  { t: "Tesauros", d: "Alta", q: "Si 'mamiferos TG animales', entonces animales es...", a: 0, o: ["Termino generico", "Termino especifico", "Termino relacionado", "Nota de historia"], e: "TG identifica el termino generico o superordinado.", h: "Lee la relacion hacia arriba: mamiferos pertenece a una clase mas amplia." },
  { t: "Tesauros", d: "Alta", q: "Si 'animales TE mamiferos', entonces mamiferos es...", a: 1, o: ["Termino generico", "Termino especifico", "Termino no controlado", "Definicion"], e: "TE identifica el termino especifico o subordinado.", h: "Lee la relacion hacia abajo: animales contiene subclases, una de ellas mamiferos." },
  { t: "Tesauros", d: "Media", q: "Una nota NH sirve para...", a: 3, o: ["Dar el precio del documento", "Registrar un enlace web", "Indicar el ISBN", "Explicar la historia de uso de un termino"], e: "NH es nota de historia, como indicar desde cuando se introdujo un termino.", h: "NH no define el concepto; cuenta algo sobre el uso historico del termino." },
  { t: "Tesauros", d: "Media", q: "DEF en la gramatica de tesauros se usa para...", a: 0, o: ["Dar una definicion del termino", "Enviar a otro descriptor", "Marcar termino generico", "Registrar una fecha cronologica"], e: "DEF introduce definiciones, como el ejemplo de claroscuro.", h: "La abreviatura casi lo dice: DEF se relaciona con definir." },
  { t: "Tesauros", d: "Alta", q: "Cual forma respeta la recomendacion sobre articulos iniciales?", a: 2, o: ["Las Artes", "El Estado siempre", "Artes", "Los documentos"], e: "El material recomienda omitir articulos iniciales: Artes mejor que las Artes.", h: "En terminos preferentes se suele evitar empezar por articulos cuando no forman parte del nombre propio." },
  { t: "Tesauros", d: "Alta", q: "Cual caso justifica retener el articulo inicial?", a: 1, o: ["Las artes como tema general", "El Salvador como pais", "El estado como concepto politico", "La fotocopia como proceso"], e: "El Salvador es un nombre propio donde el articulo forma parte del nombre.", h: "La excepcion ocurre cuando el articulo pertenece al nombre oficial o reconocido." },

  { t: "Registros bibliograficos", d: "Base", q: "En el ejemplo MARC, 040 se relaciona con...", a: 2, o: ["Titulo preferido", "ISBN", "Origen de la catalogacion", "Nota de sumario"], e: "040 registra el origen de la catalogacion, como Biblioteca EBCI, idioma y norma.", h: "Busca el campo que identifica quien hizo o de donde procede la catalogacion." },
  { t: "Registros bibliograficos", d: "Media", q: "El campo 041 del ejemplo registra...", a: 0, o: ["Idiomas", "Genero literario", "Punto cronologico", "Materia"], e: "041 aparece como campo de idiomas, con $a spa y $h fre.", h: "La pista esta en los codigos spa y fre: son codigos de lengua." },
  { t: "Registros bibliograficos", d: "Media", q: "El campo 082 se asocia con...", a: 3, o: ["Localizacion electronica", "Genero o forma", "Resumen", "Numero de clasificacion Dewey"], e: "082 corresponde al numero de clasificacion Dewey.", h: "Dewey es clasificacion; no es un resumen ni un enlace." },
  { t: "Registros bibliograficos", d: "Alta", q: "El campo 856 se utiliza para...", a: 1, o: ["Fechas asociadas", "Localizacion y acceso electronicos", "Termino cronologico", "Nombre geografico"], e: "856 registra localizacion y acceso electronicos, como un URL.", h: "Cuando veas un enlace o URL en MARC, piensa en acceso electronico." },
  { t: "Registros bibliograficos", d: "Media", q: "En Dublin Core, dc.creator corresponde a...", a: 0, o: ["Saint-Exupery como creador", "El resumen de la obra", "El pais de cobertura", "El formato computadora"], e: "dc.creator registra al creador o autor de la obra.", h: "Creator en Dublin Core se parece al autor o responsable principal." },
  { t: "Registros bibliograficos", d: "Media", q: "En Dublin Core, dc.subject se usa para...", a: 2, o: ["La editorial", "La extension fisica", "Materias como literatura europea, imaginacion o novela", "La URL del recurso"], e: "dc.subject registra los temas o materias del recurso.", h: "Subject significa asunto o tema: busca materias, no datos de publicacion." }
];

window.QUESTIONS.push(...window.EXTRA_QUESTIONS);

window.topicColors = {
  "Analisis documental": "#246b8f",
  "Indizacion": "#2f7d52",
  "Resumenes documentales": "#bd7b1f",
  "Tipos de resumen": "#6b5a9a",
  "Lenguajes documentales": "#17706c",
  "Tesauros": "#8d5a2b",
  "Registros bibliograficos": "#b44a43"
};
